/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./api/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Author: { // root type
    firstName?: string | null; // String
    id?: number | null; // Int
    lastName?: string | null; // String
  }
  Mutation: {};
  Post: { // root type
    authorId?: number | null; // Int
    body?: string | null; // String
    id?: number | null; // Int
    published?: boolean | null; // Boolean
    title?: string | null; // String
  }
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Author: { // field return type
    firstName: string | null; // String
    id: number | null; // Int
    lastName: string | null; // String
    posts: Array<NexusGenRootTypes['Post'] | null> | null; // [Post]
  }
  Mutation: { // field return type
    createAuthor: NexusGenRootTypes['Author']; // Author!
    createDraft: NexusGenRootTypes['Post']; // Post!
    publishDraft: NexusGenRootTypes['Post'] | null; // Post
    recallPost: NexusGenRootTypes['Post'] | null; // Post
    removeAuthor: NexusGenRootTypes['Author'] | null; // Author
    removePost: NexusGenRootTypes['Post'] | null; // Post
    updateDraft: NexusGenRootTypes['Post'] | null; // Post
  }
  Post: { // field return type
    author: NexusGenRootTypes['Author'] | null; // Author
    authorId: number | null; // Int
    body: string | null; // String
    id: number | null; // Int
    published: boolean | null; // Boolean
    title: string | null; // String
  }
  Query: { // field return type
    allAuthors: Array<NexusGenRootTypes['Author'] | null> | null; // [Author]
    allPosts: Array<NexusGenRootTypes['Post'] | null> | null; // [Post]
    author: NexusGenRootTypes['Author'] | null; // Author
    draftPosts: Array<NexusGenRootTypes['Post'] | null>; // [Post]!
    post: NexusGenRootTypes['Post'] | null; // Post
    publishedPosts: Array<NexusGenRootTypes['Post'] | null> | null; // [Post]
  }
}

export interface NexusGenFieldTypeNames {
  Author: { // field return type name
    firstName: 'String'
    id: 'Int'
    lastName: 'String'
    posts: 'Post'
  }
  Mutation: { // field return type name
    createAuthor: 'Author'
    createDraft: 'Post'
    publishDraft: 'Post'
    recallPost: 'Post'
    removeAuthor: 'Author'
    removePost: 'Post'
    updateDraft: 'Post'
  }
  Post: { // field return type name
    author: 'Author'
    authorId: 'Int'
    body: 'String'
    id: 'Int'
    published: 'Boolean'
    title: 'String'
  }
  Query: { // field return type name
    allAuthors: 'Author'
    allPosts: 'Post'
    author: 'Author'
    draftPosts: 'Post'
    post: 'Post'
    publishedPosts: 'Post'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createAuthor: { // args
      firstName: string; // String!
      lastName: string; // String!
    }
    createDraft: { // args
      authorId: number; // Int!
      body: string; // String!
      title: string; // String!
    }
    publishDraft: { // args
      draftId: number; // Int!
    }
    recallPost: { // args
      postId: number; // Int!
    }
    removeAuthor: { // args
      authorId: number; // Int!
    }
    removePost: { // args
      postId: number; // Int!
    }
    updateDraft: { // args
      body?: string | null; // String
      draftId: number; // Int!
      title?: string | null; // String
    }
  }
  Query: {
    author: { // args
      authorId: number; // Int!
    }
    post: { // args
      postId: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}